### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by jobs-git** [jobs-git/system-monitor#1]
**High priority**
- [x] Making the three buttons in headerbar move in the center like in Gnome System Monitor.
- [x] GtkStack
- [x] GtkStackSwitcher for switching window content
- [x] Process list like in Gnome System Monitor
- [x] Implement sorting process by name
- [x] Implement sorting process by mem usage
- [x] Implement sorting process by cpu usage
- [x] Implement end task
- [ ] GtkStackSwitcher for switching for cpu, memory, network, disk, gpu, etc.
- [ ] Dynamic cpu core

**Low priority**
- [ ] Create CentOS 7 package & submit to epel
- [ ] Fix file system 
- [ ] Speed up Cairo rendering
- [ ] Implement switch to total cpu & show cpu core graph
- [ ] Implement GtkStack for Ram, Disk & Network
